### ISSUE TITLE
Selecting all imaging columns and typical spectro columns in IQS returns runtime error

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#51] opened 2015-07-28 17:44 UTC
Running s_imaging_query_form_12 test on the SkyServer Imaging Query Form (IQS) results in a runtime error that gives the error message "Server Error in '/SkyServer' Application." along with application error details that are hidden because of web.config settings.

**Comment by mtaghiza** [comment] 2015-08-12 17:00
Fixed. It was an SkyserverWS problem. An issue with explanations was created in the SkyserverWS repository (what happens is that the response string becomes too long, surpassing the default limit).

**Comment by raddick** [comment] 2015-08-18 21:41
This is a duplicate of #34. Filing as duplicate.

**Closed by raddick** 2015-08-18 21:41 UTC
Labels: bug, duplicate, sciserver_v1_0_1
