### ISSUE TITLE
Broken "Fit Parameters" link in Explore tool

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#23] opened 2015-07-14 15:10 UTC
Test s_explore_30:
link:

http://scitest02.pha.jhu.edu/Skyserver/en/tools/explore/parameters.aspx?id=1237668296598749280&spec=2947691243863304192&apid=apogee.apo25m.s.stars.4128.2M13102744+1826172&field=0x112d14c220880000

**Comment by raddick** [comment] 2015-07-23 16:18
The problem is in the parameters.aspx file.

**Comment by mtaghiza** [comment] 2015-08-04 20:57
Fixed parameters.aspx. The RunCasJobs was missing a second parameter. Not closing for now until it is tested.

**Comment by raddick** [comment] 2015-08-18 19:42
Seems to be working fine in sciserver_v1_2_0:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/explore/parameters.aspx?id=1237668296598749280&spec=2947691243863304192&apid=apogee.apo25m.s.stars.4128.2M13102744+1826172&field=0x112d14c220880000

Closing issue.

**Closed by raddick** 2015-08-18 19:42 UTC
Labels: bug, needstest, sciserver_v1_0_0
