### ISSUE TITLE
Changing u,g,r,i or z magnitude limits does not change resultset in Radial and Rectangular search Forms

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#27] opened 2015-07-20 18:08 UTC
Tests: s_rad_search_6, s_rad_search_7, s_rect_search_6 and s_rect_search_7

**Comment by thakar** [comment] 2015-08-11 21:46
The magnitude cuts are being applied even when they are not checked, and the actual values are being ignored - the SQL query shows all magnitude cuts being applied, with fixed limits no matter whether the user checks any of the checkboxes or changes the limits:

... AND p.u between 0 AND 30 AND p.g between 0 AND 20 AND p.i between 0 AND 20 AND p.r between 0 AND 20 AND p.z between 0 AND 20 

Note that the u limit is 0 to 30 (not 20).

**Comment by mtaghiza** [comment] 2015-08-12 13:39
Fixed. Correct behavior will show in the next version.

**Comment by raddick** [comment] 2015-08-18 20:01
Working in sciserver_v1_2_0

Although even if you enter values in the textboxes, you still have to check the checkbox to make the tool pay attention to the values you entered. That's weird from a usability point of view.

**Comment by raddick** [comment] 2015-08-19 12:53
Removing the "bug" label since it works the way it was intended.

Was planning to add an "enhancement" label to track that we should improve usability here, but I'll file it as a new issue instead.

Closing this one since it's verified as being fixed in v1_2_0.

**Closed by raddick** 2015-08-19 12:53 UTC
Labels: sciserver_v1_0_0, sciserver_v1_1_0
