### ISSUE TITLE
Proximity queries in IQS and SQS return runtime errors.

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#52] opened 2015-07-28 17:46 UTC
Trying tests s_imaging_query_form_14, s_imaging_query_form_15 and s_imaging_query_form_16 to test the Proximity Search option in the Imaging Query Form (IQS) each results in runtime errors with the "Server Error in '/SkyServer' Application." error message.

**Comment by thakar** [comment] 2015-07-28 21:22
Same problem for tests s_spectro_query_form_14 through _16.

**Comment by raddick** [comment] 2015-08-07 18:29
Is this a duplicate of #33?

**Comment by mtaghiza** [comment] 2015-08-12 17:02
Fixed. Correct behavior will show in next version.

**Comment by raddick** [comment] 2015-08-19 13:55
Yes, this is a duplicate of #33, which is now fixed and verified.

Labeling this one as "duplicate" and closing.

**Closed by raddick** 2015-08-19 13:55 UTC
Labels: bug, duplicate, sciserver_v1_0_1
